### ISSUE TITLE
Port boto 3 AWS API data_utils functions to Team Repo

### ISSUE THREAD

**Issue by sharonm6** [UC-Irvine-CS175/final-project-shenanigans#2]
### Description
- Port and adapt boto 3 AWS API data_utils functions to Team Repo

### Files
- data_utils.py

### To Adapt
- Revisit filepaths
- Inform project directory structure

### Tasks
- [ ] Copy data_utils.py from download-dataset-augmentations-dataloader to repo
- [ ] Double check filepaths
- [ ] Setup directory structure
